#!/bin/bash
set -e

echo $(dirname $0)

cp dist/${PROJECT}-${VERSION}.tar.gz package/${PROJECT}.tar.gz

cp requirements.txt package/requirements.txt

cp pip.conf package/pip.conf

cp main.py package/main.py

cd package/

docker build -t ${PROJECT}:${VERSION} .